<?php

namespace MSI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository {

    public function findByZipcodeCitySelect() {
        $qb = $this->_em->createQuery('SELECT z.zipcode, c.label, c.id FROM MSICoreBundle:City AS c LEFT JOIN c.zipcode AS z GROUP BY z.zipcode, c.label');
        $cities = $qb->getArrayResult();        
        return $cities;
    }

}
