<?php

namespace MSI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends EntityRepository {

    //Récupère le premier paramètre enregistré en base 
    //@Todo plus tard lorsqu'il y aura plusieurs logiciels, faire un getSetting
    //avec id en paramètre
    public function getSetting() {
        $setting = $this->findAll();
        if (empty($setting)) {
            return false;
        } else {
            return array_shift($setting);
        }
    }

}
