<?php

namespace MSI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ZipcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipcodeRepository extends EntityRepository
{
}
