msi_core_admin_index:
    path:     /
    defaults: { _controller: MSICoreBundle:Administration:index }

msi_core_admin_users:
    path:     /users
    defaults: { _controller: MSICoreBundle:Administration:users }

msi_core_admin_settings:
    path:     /settings
    defaults: { _controller: MSICoreBundle:Administration:settings }
