msi_user:
    resource: "@MSIUserBundle/Resources/config/routing.yml"
    prefix:   /

msi_core:
    resource: "@MSICoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"