msi_user_admin_add_user:
    path:     /admin/addUser
    defaults: { _controller: MSIUserBundle:Registration:register }
    
msi_user_admin_user_edit:
    path:     /admin/editUser/{id}
    defaults: { _controller: MSIUserBundle:EditUser:edit }
    requirements:
        id: \d+