msi_user_admin_add_user:
    path:     /admin/addUser
    defaults: { _controller: MSIUserBundle:Registration:register }
msi_user_admin_edit_user:
    path:     /admin/editUser/{id}
    defaults: { _controller: MSIUserBundle:EditUser:edit}
    requirements: 
        id: \d+
msi_user_admin_edit_avatar_user:
    path:     /admin/avatarUser/{id}
    defaults: { _controller: MSIUserBundle:EditUser:editAvatar}
    requirements: 
        id: \d+
msi_user_admin_edit_pwd_user:
    path:     /admin/pwdUser/{id}
    defaults: { _controller: MSIUserBundle:EditUser:editPassword}
    requirements: 
        id: \d+
 # Profile utilisateur connecté       
msi_user_edit_user:
    path:     /myprofile/edit
    defaults: { _controller: MSIUserBundle:ProfileUser:edit}
msi_user_edit_avatar_user:
    path:     /myprofile/avatar
    defaults: { _controller: MSIUserBundle:ProfileUser:editAvatar}
msi_user_edit_pwd_user:
    path:     /myprofile/pwd
    defaults: { _controller: MSIUserBundle:ProfileUser:editPassword}
msi_user_admin_view_user:
    path:     /admin/viewUser/{id}
    defaults: { _controller: MSIUserBundle:ProfileUser:view}
    requirements: 
        id: \d+