msi_user_admin_add_user:
    path:     /admin/addUser
    defaults: { _controller: MSIUserBundle:Registration:register }
msi_user_admin_edit_user:
    path:     /admin/editUser/{id}
    defaults: { _controller: MSIUserBundle:EditUser:edit}
    requirements: 
        id: \d+
msi_user_admin_edit_avatar_user:
    path:     /admin/avatarUser/{id}
    defaults: { _controller: MSIUserBundle:EditUser:editAvatar}
    requirements: 
        id: \d+
msi_user_profile_edit_avatar:
    path:     /profile/edit/avatar/{avatarActif}
    defaults: { _controller: MSIUserBundle:ProfileUser:editProfileAvatar, avatarActif: false}
