<?php

namespace MSI\MembersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembersRepository extends EntityRepository {

    public function findMembersByParametres($data) {
        $query = $this->createQueryBuilder('m');
        if ($data['firstname'] != '') {
            $query->andWhere('m.firstname LIKE :firstname')
                    ->setParameter('firstname', '%' . $data['firstname'] . '%');
        }
        if ($data['lastname'] != '') {
            $query->andWhere('m.firstname LIKE :firstname')
                    ->setParameter('firstname', '%' . $data['firstname'] . '%');
        }
        if ($data['email'] != '') {
            $query->andWhere('m.firstname LIKE :firstname')
                    ->setParameter('email', '%' . $data['email'] . '%');
        }
        if ($data['zipcode'] != '') {
            // this field is still not field voir pour un join avec city et zipcode
            $query->orWhereWhere('m.zipcode = :zipcode')
                    ->setParameter('zipcode', $data['zipcode']);
        }
        if ($data['address'] != '') {
            $query->andWhere('m.address LIKE :address')
                    ->setParameter('address', '%' . $data['address'] . '%');
        }
        if ($data['phone'] != '') {
            $query->andWhere('m.phone = :phone')
                    ->setParameter('phone', $data['phone']);
        }
        if ($data['mobile'] != '') {
            $query->andWhere('m.mobile = :mobile')
                    ->setParameter('mobile', $data['mobile']);
        }
        if (!empty($data['familySituation'])) {
            $query->andWhere('m.family_situation IN (:familySituation)')
                    ->setParameter('familySituation', $data['familySituation']);
        }
        if ($data['sex'] != '') {
            $query->orWhereWhere('m.sex = :sex')
                    ->setParameter('zipcode', $data['sex']);
        }
        if (!empty($data['city'])) {
            $query->andWhere('m.city IN (:city)')
                    ->setParameter('city', $data['city']);
        }
        if ($data['activeMember'] != '') {
            $query->orWhereWhere('m.sex = :sex')
                    ->setParameter('zipcode', $data['activeMember']);
        }

        return $query->getQuery()->getResult();
    }

}
