<?php

namespace MSI\MembersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Pro_social_categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pro_social_categoriesRepository extends EntityRepository
{
}
