<?php

namespace MSI\MembersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Scolar_categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Scolar_categoriesRepository extends EntityRepository
{
}
